-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 15:55:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locations` (
  `LocationID` SMALLINT NOT NULL,
  `NumbMeters` INT NULL,
  `Name` TEXT NOT NULL,
  PRIMARY KEY (`LocationID`),
  UNIQUE INDEX `Name_UNIQUE` (`LocationID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meters` (
  `SerialNumb` TEXT NOT NULL,
  `id` TEXT NOT NULL,
  `RegisterYear` SMALLINT NOT NULL,
  `Model` TEXT NOT NULL,
  `Version` TEXT NOT NULL,
  `Locations_LocationID` INT NOT NULL,
  `Manufacturer` TEXT NOT NULL,
  PRIMARY KEY (`SerialNumb`, `Locations_LocationID`, `Manufacturer`),
  UNIQUE INDEX `SerialNumb_UNIQUE` (`SerialNumb` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Meters_Locations_idx` (`Locations_LocationID` ASC) VISIBLE,
  CONSTRAINT `fk_Meters_Locations`
    FOREIGN KEY (`Locations_LocationID`)
    REFERENCES `mydb`.`Locations` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModbusQueries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ModbusQueries` (
  `Serial` INT NOT NULL,
  `Modbus_Address` JSONB NOT NULL,
  `Parameter_description` TEXT NOT NULL,
  `Standard` TEXT NOT NULL,
  `data_type` TEXT NOT NULL,
  `data_range` TEXT NOT NULL,
  `Model` TEXT NOT NULL,
  `Default` TEXT NOT NULL,
  `Register number` SMALLINT NOT NULL,
  `Meters_Manufacturer` TEXT NOT NULL,
  PRIMARY KEY (`Serial`, `Meters_Manufacturer`),
  UNIQUE INDEX `SerialAddress_UNIQUE` (`Serial` ASC) VISIBLE,
  UNIQUE INDEX `Modbus_Address_UNIQUE` (`Modbus_Address` ASC) VISIBLE,
  INDEX `fk_ModbusQueries_Meters1_idx` (`Meters_Manufacturer` ASC) VISIBLE,
  CONSTRAINT `fk_ModbusQueries_Meters1`
    FOREIGN KEY (`Meters_Manufacturer`)
    REFERENCES `mydb`.`Meters` (`Manufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Measurements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Measurements` (
  `idMeasurements` INT GENERATED ALWAYS AS () VIRTUAL,
  `Timestamp` TEXT NOT NULL,
  `amps_total` SMALLINT NOT NULL,
  `amps_phase_a` SMALLINT NOT NULL,
  `amps_phase_b` SMALLINT NOT NULL,
  `amps_phase_c` SMALLINT NOT NULL,
  `volatge_ln_average` SMALLINT) NOT NULL,
  `phase_voltage_an` SMALLINT NOT NULL,
  `phase_voltage_bn` SMALLINT NOT NULL,
  `phase_voltage_cn` SMALLINT NOT NULL,
  `voltage_ll_average` SMALLINT NOT NULL,
  `phase_voltage_ab` SMALLINT NOT NULL,
  `phase_voltage_bc` SMALLINT NOT NULL,
  `phase_voltage_ca` SMALLINT NOT NULL,
  `frequency` SMALLINT NOT NULL,
  `total_real_power` SMALLINT NOT NULL,
  `watts_phase_a` SMALLINT NOT NULL,
  `watts_phase_b` SMALLINT NOT NULL,
  `watts_phase_c` SMALLINT NOT NULL,
  `ac_apparent_power_va` SMALLINT NOT NULL,
  `va_phase_a` SMALLINT NOT NULL,
  `va_phase_b` SMALLINT NOT NULL,
  `va_phase_c` SMALLINT NOT NULL,
  `reactive_power_var` SMALLINT NOT NULL,
  `var_phase_a` SMALLINT NOT NULL,
  `var_phase_b` SMALLINT NOT NULL,
  `var_phase_c` SMALLINT NOT NULL,
  `power_factor` SMALLINT NOT NULL,
  `pf_phase_a` SMALLINT NOT NULL,
  `pf_phase_b` SMALLINT NOT NULL,
  `pf_phase_c` SMALLINT NOT NULL,
  `total_real_energy_exported` INT NOT NULL,
  `total_watt_hours_exported_in_phase_a` INT NOT NULL,
  `total_watt_hours_exported_in_phase_b` INT NOT NULL,
  `total_watt_hours_exported_in_phase_c` INT NOT NULL,
  `total_real_energy_imported` INT NOT NULL,
  `total_watt_hours_imported_in_phase_a` INT NOT NULL,
  `total_watt_hours_imported_in_phase_b` INT NOT NULL,
  `total_watt_hours_imported_in_phase_c` INT NOT NULL,
  `total_va_hours_exported` INT NOT NULL,
  `total_va_hours_exported_phase_b` INT NOT NULL,
  `total_va_hours_exported_phase_b` INT NOT NULL,
  `total_va_hours_exported_phase_c` INT NOT NULL,
  `total_va_hours_imported` INT NOT NULL,
  `total_va_hours_imported_phase_a` INT NOT NULL,
  `total_va_hours_imported_phase_b` INT NOT NULL,
  `total_va_hours_imported_phase_c` INT NOT NULL,
  `total_var_hours_imported_q1` INT NOT NULL,
  `total_var_hours_imported_q1_phase_a` INT NOT NULL,
  `total_var_hours_imported_q1_phase_b` INT NOT NULL,
  `total_var_hours_imported_q1_phase_c` INT NOT NULL,
  `total_var_hours_imported_q2` INT NOT NULL,
  `total_var_hours_imported_q2_phase_a` INT NOT NULL,
  `total_var_hours_imported_q2_phase_b` INT NOT NULL,
  `total_var_hours_imported_q2_phase_c` INT NOT NULL,
  `total_var_hours_imported_q3` INT NOT NULL,
  `total_var_hours_imported_q3_phase_a` INT NOT NULL,
  `total_var_hours_imported_q3_phase_b` INT NOT NULL,
  `total_var_hours_imported_q3_phase_c` INT NOT NULL,
  `total_var_hours_imported_q4` INT NOT NULL,
  `total_var_hours_imported_q4_phase_a`INT NOT NULL,
  `total_var_hours_imported_q4_phase_b` INT NOT NULL,
  `total_var_hours_imported_q4_phase_c` INT NOT NULL,
  `Meters_SerialNumb` INT NOT NULL,
  `Meters_Locations_LocationID` INT NOT NULL,
  PRIMARY KEY (`idMeasurements`, `Meters_SerialNumb`, `Meters_Locations_LocationID`),
  INDEX `fk_Measurements_Meters1_idx` (`Meters_SerialNumb` ASC, `Meters_Locations_LocationID` ASC) VISIBLE,
  CONSTRAINT `fk_Measurements_Meters1`
    FOREIGN KEY (`Meters_SerialNumb` , `Meters_Locations_LocationID`)
    REFERENCES `mydb`.`Meters` (`SerialNumb` , `Locations_LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
