CREATE TABLE measurement_address (
	id SERIAL PRIMARY KEY,
	modbus_address_DEC JSONB,
	parameter_description TEXT
);

INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4167'::jsonb, 'amps_total');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4168'::jsonb, 'amps_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4169'::jsonb, 'amps_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4170'::jsonb, 'amps_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4172'::jsonb, 'voltage_ln_average');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4173'::jsonb, 'phase_voltage_an');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4174'::jsonb, 'phase_voltage_bn');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4175'::jsonb, 'phase_voltage_cn');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4176'::jsonb, 'voltage_ll_average');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4177'::jsonb, 'phase_voltage_ab');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4178'::jsonb, 'phase_voltage_bc');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4179'::jsonb, 'phase_voltage_ca');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4181'::jsonb, 'frequency');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4183'::jsonb, 'total_real_power');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4184'::jsonb, 'watts_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4185'::jsonb, 'watts_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4186'::jsonb, 'watts_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4188'::jsonb, 'ac_apparent_power_va');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4189'::jsonb, 'va_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4190'::jsonb, 'va_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4191'::jsonb, 'va_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4193'::jsonb, 'reactive_power_var');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4194'::jsonb, 'var_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4195'::jsonb, 'var_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4196'::jsonb, 'var_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4198'::jsonb, 'power_factor');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4199'::jsonb, 'pf_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4200'::jsonb, 'pf_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('4201'::jsonb, 'pf_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4203, 4204]'::jsonb, 'total_real_energy_exported');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4205, 4206]'::jsonb, 'total_watt_hours_exported_in_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4207, 4208]'::jsonb, 'total_watt_hours_exported_in_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4209, 4210]'::jsonb, 'total_watt_hours_exported_in_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4211, 4212]'::jsonb, 'total_real_energy_imported');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4213, 4214]'::jsonb, 'total_watt_hours_imported_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4215, 4216]'::jsonb, 'total_watt_hours_imported_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4217, 4218]'::jsonb, 'total_watt_hours_imported_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4220, 4221]'::jsonb, 'total_va_hours_exported');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4222, 4223]'::jsonb, 'total_va_hours_exported_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4224, 4225]'::jsonb, 'total_va_hours_exported_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4226, 4227]'::jsonb, 'total_va_hours_exported_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4228, 4229]'::jsonb, 'total_va_hours_imported');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4230, 4231]'::jsonb, 'total_va_hours_imported_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4232, 4233]'::jsonb, 'total_va_hours_imported_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4234, 4235]'::jsonb, 'total_va_hours_imported_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4237, 4238]'::jsonb, 'total_var_hours_imported_q1');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4239, 4240]'::jsonb, 'total_var_hours_imported_q1_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4241, 4242]'::jsonb, 'total_var_hours_imported_q1_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4243, 4244]'::jsonb, 'total_var_hours_imported_q1_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4245, 4246]'::jsonb, 'total_var_hours_imported_q2');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4247, 4248]'::jsonb, 'total_var_hours_imported_q2_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4249, 4250]'::jsonb, 'total_var_hours_imported_q2_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4251, 4252]'::jsonb, 'total_var_hours_imported_q2_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4253, 4254]'::jsonb, 'total_var_hours_exported_q3');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4255, 4256]'::jsonb, 'total_var_hours_exported_q3_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4257, 4258]'::jsonb, 'total_var_hours_exported_q3_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4259, 4260]'::jsonb, 'total_var_hours_exported_q3_phase_c');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4261, 4262]'::jsonb, 'total_var_hours_exported_q4');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4263, 4264]'::jsonb, 'total_var_hours_exported_q4_phase_a');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4265, 4266]'::jsonb, 'total_var_hours_exported_q4_phase_b');
INSERT INTO measurement_address (modbus_address_DEC, parameter_description) VALUES ('[4267, 4268]'::jsonb, 'total_var_hours_exported_q4_phase_c');